environment:
  matrix:
  - nodejs_version: "7"
  - nodejs_version: "8"

cache:
  - '%LOCALAPPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - npm --version
  - npm test
